export const WALLET_UPDATE_DATA = 'WALLET_UPDATE_DATA'
export const WALLET_UPDATE_META = 'WALLET_UPDATE_META'
export const WALLET_UPDATE_STATUS = 'WALLET_UPDATE_STATUS'

export const FACEBOOK_UPDATE_DATA = 'FACEBOOK_UPDATE_DATA'
export const FACEBOOK_UPDATE_AUTHENTICATION_STATUS = 'FACEBOOK_UPDATE_AUTHENTICATION_STATUS'

export const SUPPORT_SEND_REQUESTED = 'SUPPORT_SEND_REQUESTED'
export const SUPPORT_SEND_SUCCEEDED = 'SUPPORT_SEND_SUCCEEDED'
export const SUPPORT_SEND_FAILED = 'SUPPORT_SEND_FAILED'

export const ACHIEVEMENT_CONFIRM_REQUESTED = 'ACHIEVEMENT_CONFIRM_REQUESTED'
export const ACHIEVEMENT_CONFIRM_SUCCEEDED = 'ACHIEVEMENT_CONFIRM_SUCCEEDED'
export const ACHIEVEMENT_CONFIRM_FAILED = 'ACHIEVEMENT_CONFIRM_FAILED'

export const STREAM_FETCH_ACHIEVEMENTS_REQUESTED = 'STREAM_FETCH_ACHIEVEMENTS_REQUESTED'
export const STREAM_FETCH_ACHIEVEMENTS_SUCCEEDED = 'STREAM_FETCH_ACHIEVEMENTS_SUCCEEDED'
export const STREAM_FETCH_ACHIEVEMENTS_FAILED = 'STREAM_FETCH_ACHIEVEMENTS_FAILED'
