export const STORE_WALLET_INFO = 'STORE_WALLET_INFO'

export const SUPPORT_SEND_REQUESTED = 'SUPPORT_SEND_REQUESTED'
export const SUPPORT_SEND_SUCCEEDED = 'SUPPORT_SEND_SUCCEEDED'
export const SUPPORT_SEND_FAILED = 'SUPPORT_SEND_FAILED'
